name: CI
on:
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened, closed]
env:
  SONAR_BRANCH_NAME: ${{ github.base_ref }}
  SONAR_RESULT_STATUS: STATUS
jobs:
  build:
    name: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run coverage
        run: |
          coverage run test_sparking.py
          coverage xml
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: |
#          echo "$GITHUB_CONTEXT"

      - name: Upload pytest test results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.xml

  sonar:
    name: SonarQube Scan
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare head branch name
        if: ${{ github.event.action != 'closed' }}
        run: echo "SONAR_BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Prepare base branch name
        if: ${{ github.event.action == 'closed' }}
        run: echo "SONAR_BRANCH_NAME=${{ github.base_ref }}" >> $GITHUB_ENV

      - name: Prepare vars
        id: vars
        run: |
          echo ::set-output name=repo::${GITHUB_REPOSITORY#*/} | tr / -
          echo ::set-output name=branch::${SONAR_BRANCH_NAME} | tr / -
          echo ::set-output name=del_branch::${{ github.head_ref }} | tr / -

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3

      - name: Run sonar-scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: sonar-scanner
          -Dsonar.projectKey=${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.branch }}
          -Dsonar.exclusions='**/tests/**, **/all_migrations/**'
          -Dsonar.qualitygate.wait=true

      - name: Get sonar results
        id: result
        if: ${{ github.event.action != 'closed' }}
        run: |
          sleep 10
          PROJECT_STATUS=$(curl -u ${{ secrets.SONAR_TOKEN }} -X POST -d 'projectKey=${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.branch }}' https://sonar.turingvideo.cn/api/qualitygates/project_status)
          PROJECT_STATUS_STATUS="$( echo $PROJECT_STATUS | jq -r '.projectStatus.status' )"
          echo $PROJECT_STATUS
          echo "Status: $PROJECT_STATUS_STATUS"
          echo ::set-output name=status::${PROJECT_STATUS_STATUS}

      - name: Finish report check if everything is ok
        uses: LouisBrunner/checks-action@v1.1.2
        if: ${{ github.event.action != 'closed' && steps.result.outputs.status != 'ERROR' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: SonarQube Report
          conclusion: success
          output: |
            { "summary": "View more details on [SonarQube](https://sonar.turingvideo.cn/dashboard?id=${{ steps.vars.outputs.repo }}%3A${{ steps.vars.outputs.branch }})." }

      - name: Fail report check if the status of the sonar result is error
        uses: LouisBrunner/checks-action@v1.1.2
        if: ${{ github.event.action != 'closed' && steps.result.outputs.status == 'ERROR' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: SonarQube Report
          conclusion: failure
          output: |
            { "summary": "View more details on [SonarQube](https://sonar.turingvideo.cn/dashboard?id=${{ steps.vars.outputs.repo }}%3A${{ steps.vars.outputs.branch }})." }

      - name: Delete branch report if merged
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged == true }}
        run: |
          curl -u ${{ secrets.SONAR_TOKEN }} -X POST -d 'project=${{ steps.vars.outputs.repo }}:${{ steps.vars.outputs.del_branch }}' https://sonar.turingvideo.cn/api/projects/delete
